### ISSUE TITLE
is Sopcast/Acestream still needed?

### ISSUE THREAD

**Issue by maxdd** [alesnav/p2ptv-pi#6]
Hello,
do i need to install Sopcast first? if so, there is not armhf version of sopcast nor acestream.
I keep getting the following message: 
El proceso SOPCAST ya no existe.

I'm using an odroid which is armv7 do i need to recompile qemu-i386?

**Comment by maxdd** [comment]
i found that i have a problem here

try:
    import apsw
except:
    print >> sys.stderr, 'not using apsw'

**Comment by maxdd** [comment]
not using apsw
2016-04-04 20:22:40 get_default_api_version: 2
2016-04-04 20:22:40 build 2233
2016-04-04 20:22:40 version 2.0.8.12
No existing database found. Attempting to creating a new database u'/root/.ACEStream/sqlite/torrentstream.sdb'
Traceback (most recent call last):
  File "start.py", line 7, in <module>
    start(apptype, curdir)
  File "/root/p2ptv/p2ptv-pi/acestream/ACEStream/Plugin/EngineConsole.py", line 43, in start
    bgapp = run_bgapp(wrapper, appname, VERSION)
  File "/root/p2ptv/p2ptv-pi/acestream/ACEStream/Plugin/BackgroundProcess.py", line 2466, in run_bgapp
    app = BackgroundApp(wrapper, 0, appname, appversion, params, installdir)
  File "/root/p2ptv/p2ptv-pi/acestream/ACEStream/Plugin/BackgroundProcess.py", line 157, in __init__
    BaseApp.__init__(self, wrapper, redirectstderrout, appname, appversion, params, installdir, i2i_port, session_port)
  File "/root/p2ptv/p2ptv-pi/acestream/ACEStream/Player/BaseApp.py", line 198, in __init__
    self.OnInitBase()
  File "/root/p2ptv/p2ptv-pi/acestream/ACEStream/Player/BaseApp.py", line 375, in OnInitBase
    self.s = Session(self.sconfig, on_error=self.on_error)
  File "/root/p2ptv/p2ptv-pi/acestream/ACEStream/Core/Session.py", line 172, in __init__
    self.lm.register(self, self.sesslock)
  File "/root/p2ptv/p2ptv-pi/acestream/ACEStream/Core/APIImplementation/LaunchManyCore.py", line 75, in register
    cachedb.init(config, self.rawserver_fatalerrorfunc)
  File "/root/p2ptv/p2ptv-pi/acestream/ACEStream/Core/CacheDB/sqlitecachedb.py", line 54, in init
    sqlitedb.initDB(sqlite_db_path, CREATE_SQL_FILE)
  File "/root/p2ptv/p2ptv-pi/acestream/ACEStream/Core/CacheDB/sqlitecachedb.py", line 227, in initDB
    self.safelyOpenACEStreamDB(sqlite_filepath, create_sql_filename, busytimeout, check_version=check_version, current_db_version=current_db_version)
  File "/root/p2ptv/p2ptv-pi/acestream/ACEStream/Core/CacheDB/sqlitecachedb.py", line 259, in safelyOpenACEStreamDB
    self.createDBTable(sql_create_tables, dbfile_path, busytimeout)
  File "/root/p2ptv/p2ptv-pi/acestream/ACEStream/Core/CacheDB/sqlitecachedb.py", line 211, in createDBTable
    cur = self.openDB(dbfile_path, busytimeout)
  File "/root/p2ptv/p2ptv-pi/acestream/ACEStream/Core/CacheDB/sqlitecachedb.py", line 201, in openDB
    con = apsw.Connection(dbfile_path)
NameError: global name 'apsw' is not defined

**Comment by russellhoff** [comment]
Hi! I currently have the same error... I don't know how to solve it, and the  owner doesn't tell us anything :(

**Comment by alesnav** [comment]
Hello,

Sorry for delay...I am not as active as before in here.

qemu-i386 is compiled to work in Raspberry and won't work in other platform, so you must recompile it.

Sorry for inconveniences.
